FROM node:20-alpine AS dev

WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-lock.yaml package.json ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000
EXPOSE 3001

CMD ["pnpm", "dev"]
